language: node_js
cache:
  directories: 
    - ~/.npm
node_js: 
  - '12'
  git:
  depth: 3
script:
  - yarn build
deploy: 
  provider: pages
  edge: true,
  skip-cleanup: true
  keep-history: true
  github-token: $GH_Token
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy released"
  on: 
    branch: master